### ISSUE TITLE
Template error: Unable to get mapping for AMIRegionMap::us-east-2::AMILinux

### ISSUE THREAD

**Issue by Starsky-burns** [cat-box/aws-foundry-ssl#1]
Thanks for all the work putting this together folks! I'm getting this error on the final screen, however.

**Comment by cat-box** [comment]
I just added support for us-east-2. As noted in the documentation, us-east-2 was not a supported region.

**Comment by Starsky-burns** [comment]
Thanks! I'm not entirely sure what that entails - sorry! I figured being in the UK this wasn't going to be an issue 😅

**Comment by zkkng** [comment]
If your players and yourself are based in UK or Europe in general consider using one of the EU regions to reduce latency.

**Comment by Starsky-burns** [comment]
Having no AWS experience whatsoever, would I change the region in CloudFormation or EC2? Thanks again for all your work 🙏

**Comment by zkkng** [comment]
It was accidently left out of the wiki, its being added shortly. To change it see the AWS guide https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/getting-started.html#select-region
