### ISSUE TITLE
I can access my Foundry install via DNS, but I have to append :30000

### ISSUE THREAD

**Issue by nadcraker** [cat-box/aws-foundry-ssl#14]
Did I miss something in the instructions?

In looking at the scripts in this repo it looks like this is an NGINX thing. I guess something went wrong there. I can manually setup the proxy I suppose.

**Comment by nadcraker** [comment]
I deleted all my resources (except Route53 NS and SOA records) and ran a new stack. Now I don't have to put in :30000. But HTTPS still does not work.

**Comment by cat-box** [comment]
I'll need a little more information from the stack to find out where it's gone awry. Could you please SSH into the ec2 instance and send me the log file located in `/tmp/foundry-setup.log`. You will first need to run the following commands

```
sudo su
chmod a+r /tmp/foundry-setup.log
```

then either use sftp/winSCP/Cyberduck to grab that file and put it up on googledrive/dropbox and send it to me in a private message on reddit.

**Comment by nadcraker** [comment]
I am impatient. Everything works fine now. My apologies.
I think the whole problem was not waiting for my domain to become ready before proceeding. The other steps rely on that.
Thank you so much for this. It really is awesome to have this whole thing setup in like 10 minutes. Very nice work. Sorry I'm a PITA.
