### ISSUE TITLE
Resolved: Unable to connect to EC2 instance

### ISSUE THREAD

**Issue by mcasto** [cat-box/aws-foundry-ssl#15]
I set everything up, and it runs great. I seem to have access through the app to everything. I added game system, a pre-built world, and an empty world ... but I can't find my User Data files for any of it. The S3 bucket I set up during this process is empty.

**Comment by mcasto** [comment]
Oh ... I may have just found it under Transferring Files in the Wiki (I really did read all of it beforehand, but by the time I got to this part of my experience, I had forgotten that section). I'll reread now & see if I can find my files. If I do, I'll close this issue.

**Comment by mcasto** [comment]
Okay. That didn't work. I'm running on Mac and use CyberDuck for all the FTP & S3 interactions I usually do.

I've triple checked all the settings, but I get an error: "Connection failed. Operation timed out. The connection attempt was rejected. The server may be down, or your network may not be properly configured."

Since the app runs properly, I can do everything I _need_ to do in it, so this is pretty low priority, but it would be nice to directly access the data files.

**Comment by mcasto** [comment]
For some reason (maybe a mistake I made in setup), my instance didn't have port 22 open. I fixed that and got into the files on ec2. I'm going change the title to reflect the actual problem I had, add another comment with the steps I took to resolve the issue (in case someone else has the same problem), then I'll close it.

**Comment by mcasto** [comment]
After following the instructions, I was unable to connect to my EC2 instance and access my foundry files.

After some digging, I discovered that port 22 (for SSH / SFTP access) was not open on my EC2 instance.

To remedy that, I went to the "Security" tab on my instance in the AWS EC2 console. There's a link there for "Security Groups" (you can also find Security Groups in the lefthand navigation, but this link was easier for me since I have other Security Groups in my console and this link took me directly where I needed to be).

Under "Inbound Rules," I had no rule for Port 22. I clicked "Edit inbound rules" > "Add rule". Then I selected "SSH" from the Type dropdown. That autofilled Port 22. I then had to designate the CIDR blocks (0.0.0.0/0).

I clicked "Save rules" and it was done.

From there, I was able to (in my case) follow the directions given to connect Cyberduck to my EC2 instance.

**Comment by cat-box** [comment]
Hey, I'm glad you were able to troubleshoot this yourself! You must have just scrolled past it, but in the Transferring Files wiki page, under [Opening Port 22](https://github.com/cat-box/aws-foundry-ssl/wiki/Transferring-Files#opening-port-22), I cover how to open port 22

**Comment by mcasto** [comment]
LOL. Yup. I somehow spaced that section.
