### ISSUE TITLE
Implement patch for SSL renewal after 30 day expiration warning, will it now auto renew?

### ISSUE THREAD

**Issue by SleepyBandit** [cat-box/aws-foundry-ssl#16]
More a question on the patch then an issue. I got an email saying my SSL encryption was set to expire in 19 days, and came here to find that a patch had been released to fix it to allow for auto renewal. I'm not entirely familiar with how Lets Encrypt does their renewals but it seems like they recommend auto renewing 30 days prior to expiration. Does that logic for the patch check regularly even after the 30 day count down begins or do I need to manually renew it this time and then in the future it will catch it at the 30 day mark?

Just looking for confirmation one way or another. Thanks for the amazing work!!

**Comment by cat-box** [comment]
Once applied, your certificate will auto-renew regardless of the days left. i.e. you do not have to manually renew your cert 

The patch checks whether or not the certificate expires in the next 30 days, as long as that is true, it will issue a renewal request.

**Comment by SleepyBandit** [comment]
Awesome. Thanks for the quick response!
