### ISSUE TITLE
GitHub guide is missing steps included in the original guide for how to change regions.

### ISSUE THREAD

**Issue by zkkng** [cat-box/aws-foundry-ssl#2]
The original guide was really great, and this definitely seems like an improvement, but it feels like some corners were cut. Specifically removing the section about how to change regions from the AWS Console.

Any chance this can get added?

**Comment by cat-box** [comment]
Yknow, if whoever was helping me build this deployment helped with the documentation **at all** I'm sure I wouldn't have missed this. Thanks for pointing it out!
