### ISSUE TITLE
SSL does not work 

### ISSUE THREAD

**Issue by Pryte** [cat-box/aws-foundry-ssl#21]
Followed the instructions: bought an .eu domain at route53 and created the stack based on the template. Foundry is installed but seems to be without a certificate. I checked crt.sh as mentioned in the troubleshooting, there is no entry for my domain. 

When I check the stack in CloudFormation it gives me the status create_complete but when I click on the stack and open the "events" tub there 50 entries of which only 17 are marked as create_complete the rest as create_in_progress. 

I deleted the stack an retried the process. Same results. 

Can anybody help?

**Comment by cat-box** [comment]
Please wait for the stack to fully complete and the EC2 machine to boot up. Once it has, wait an additional 10-20 minutes for machine configurations to finish. If you're still seeing issues, there is a log located in /tmp/foundry-setup.log.

To access, [SSH](https://github.com/cat-box/aws-foundry-ssl/wiki/SSH-Access) into the EC2 terminal and use the following commands.
```
sudo su
chmod a+r /tmp/foundry-setup.log
```
Then use WinSCP or Cyberduck to extract the file. Send it to me on reddit u/auraofire. DO NOT post it here.

**Comment by Pryte** [comment]
I made sure to delete the DNS files before creating the stack and it's been ~8h now. Is this a normal waiting time? 

Will send you the file on Sunday. Thank you!

**Comment by cat-box** [comment]
Definitely not normal. Can you send me the values you entered during setup as well?

**Comment by cat-box** [comment]
http-01 request failed at configuration. resolved with manual certificate request
