### ISSUE TITLE
Applied node patch but still can't upgrade

### ISSUE THREAD

**Issue by Stratlin** [cat-box/aws-foundry-ssl#24]
Hello and thanks for the assistance.

I applied the patch to node per the instructions, checked my node version and it is showing as upgraded (14.17.0.). When I go to my server, however, and try to upgrade foundry, I am still getting the following error:

An update to version 0.8.6 is available but cannot be performed because upgrading to this version requires a full reinstall in order to obtain Node.js version 14 and other updated dependencies. You can manually download this latest version from the Foundry Virtual Tabletop website.

Below is a log of all the processes regarding the patch. Thanks for the help!

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
[ec2-user ~]$ sudo su
[rootec2-user]# wget https://raw.githubusercontent.com/cat-box/aws-foundry-ssl/master/patches/node_v14.sh
--2021-05-31 19:24:36--  https://raw.githubusercontent.com/cat-box/aws-foundry-ssl/master/patches/node_v14.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 536 [text/plain]
Saving to: ‘node_v14.sh’

100%[======================================>] 536         --.-K/s   in 0s

2021-05-31 19:24:36 (21.6 MB/s) - ‘node_v14.sh’ saved [536/536]

[root@ip- ec2-user]# chmod a+x node_v14.sh
[root@ip- ec2-user]# ./node_v14.sh
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
228 packages excluded due to repository priority protections
No packages marked for update
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:14.17.0-1nodesource will be erased
---> Package nodesource-release.noarch 0:el7-1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package               Arch      Version                   Repository      Size
================================================================================
Removing:
 nodejs                x86_64    2:14.17.0-1nodesource     @nodesource     91 M
 nodesource-release    noarch    el7-1                     installed      3.1 k

Transaction Summary
================================================================================
Remove  2 Packages

Installed size: 91 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : nodesource-release-el7-1.noarch                              1/2
  Erasing    : 2:nodejs-14.17.0-1nodesource.x86_64                          2/2
  Verifying  : nodesource-release-el7-1.noarch                              1/2
  Verifying  : 2:nodejs-14.17.0-1nodesource.x86_64                          2/2

Removed:
  nodejs.x86_64 2:14.17.0-1nodesource     nodesource-release.noarch 0:el7-1

Complete!

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release
+ uname -m

## Confirming "el7-x86_64" is supported...

+ curl -sLf -o /dev/null 'https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Downloading release setup RPM...

+ mktemp
+ curl -sL -o '/tmp/tmp.CD9b0qRqOx' 'https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm'

## Installing release setup RPM...

+ rpm -i --nosignature --force '/tmp/tmp.CD9b0qRqOx'

## Cleaning up...

+ rm -f '/tmp/tmp.CD9b0qRqOx'

## Checking for existing installations...

+ rpm -qa 'node|npm' | grep -v nodesource

## You may also need development tools to build native addons:
     sudo yum install gcc-c++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
     sudo yum install yarn

Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Existing lock /var/run/yum.pid: another copy is running as pid 4089.
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory : 119 M RSS (335 MB VSZ)
    Started: Mon May 31 19:25:00 2021 - 00:03 ago
    State  : Running, pid: 4089
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory : 276 M RSS (493 MB VSZ)
    Started: Mon May 31 19:25:00 2021 - 00:05 ago
    State  : Running, pid: 4089
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory : 311 M RSS (528 MB VSZ)
    Started: Mon May 31 19:25:00 2021 - 00:07 ago
    State  : Running, pid: 4089
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory : 311 M RSS (527 MB VSZ)
    Started: Mon May 31 19:25:00 2021 - 00:09 ago
    State  : Running, pid: 4089
Cleaning repos: amzn2-core amzn2extra-docker amzn2extra-nginx1 epel nodesource
Cleaning up everything
Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                               | 3.7 kB     00:00
amzn2extra-docker                                        | 3.0 kB     00:00
amzn2extra-nginx1                                        | 3.0 kB     00:00
epel/x86_64/metalink                                     |  15 kB     00:00
epel                                                     | 4.7 kB     00:00
nodesource                                               | 2.5 kB     00:00
(1/11): amzn2-core/2/x86_64/group_gz                       | 2.5 kB   00:00
(2/11): amzn2-core/2/x86_64/updateinfo                     | 373 kB   00:00
(3/11): amzn2extra-nginx1/2/x86_64/primary_db              |  30 kB   00:00
(4/11): amzn2extra-docker/2/x86_64/updateinfo              |   76 B   00:00
(5/11): amzn2extra-docker/2/x86_64/primary_db              |  78 kB   00:00
(6/11): amzn2extra-nginx1/2/x86_64/updateinfo              |   76 B   00:00
(7/11): epel/x86_64/group_gz                               |  96 kB   00:00
(8/11): epel/x86_64/updateinfo                             | 1.0 MB   00:00
(9/11): nodesource/x86_64/primary_db                       |  40 kB   00:00
(10/11): epel/x86_64/primary_db                            | 6.9 MB   00:00
(11/11): amzn2-core/2/x86_64/primary_db                    |  53 MB   00:02
228 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:14.17.0-1nodesource will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package      Arch         Version                       Repository        Size
================================================================================
Installing:
 nodejs       x86_64       2:14.17.0-1nodesource         nodesource        32 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 32 M
Installed size: 91 M
Downloading packages:
nodejs-14.17.0-1nodesource.x86_64.rpm                      |  32 MB   00:01
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : 2:nodejs-14.17.0-1nodesource.x86_64                          1/1
  Verifying  : 2:nodejs-14.17.0-1nodesource.x86_64                          1/1

Installed:
  nodejs.x86_64 2:14.17.0-1nodesource

Complete!
[root@ip- ec2-user]# rm node_v14.sh
rm: remove regular file ‘node_v14.sh’? y
[root@ip- ec2-user]# node -v
v14.17.0
[root@ip-ec2-user]#

**Comment by cat-box** [comment]
Hi, please remove your IP address! I'm looking into the update method. This server should not need a new deployment since it is being hosted on its own without electron. 

As per the release notes:
>If you are hosting Foundry VTT as a dedicated server via NodeJS and already using Node 14+ you can simply update in place by selecting Release and choosing to update via the setup menu.

**Comment by Stratlin** [comment]
Oops! Thanks for the security catch. Can't believe I was so scatter brained there. Sounds good. Thanks for looking into the issue.

**Comment by cat-box** [comment]
[New patch](https://github.com/cat-box/aws-foundry-ssl/wiki/Patches#foundryvtt-update) released to work around this! This one does an automated reinstall of Foundry since I can't figure out where it's cacheing the node version. Let me know how it goes!

**Comment by Stratlin** [comment]
At some point the cache must have finally updated because I was able upgrade earlier as normal. Maybe it just takes a day or so to register? That said, hopefully the patch helps some others so they can upgrade right away. Thanks for all your hard work!
