### ISSUE TITLE
Send logs to cloudwatch

### ISSUE THREAD

**Issue by Scipi** [cat-box/aws-foundry-ssl#32]
If something goes wrong with the server or a script like the letsencrypt job fails I'd like to be able to send logs to CloudWatch for easy viewing instead of having to SSH and trawl through them with cli tools. While it should be simple enough to do this manually, having it at least an optional step to do it automatically would be useful especially in cases where we're running multiple servers.

**Comment by zkkng** [comment]
I believe this was added in the dev branch along with other fixes such as running the application as root. I never got around to testing and documenting all of it though.

**Comment by zkkng** [comment]
Resolved in v2.0
