### ISSUE TITLE
IAM Credentials do not transfer to AWS.json

### ISSUE THREAD

**Issue by cat-box** [cat-box/aws-foundry-ssl#6]

**Comment by mpstein** [comment]
Confirmed - the Secret Key isn't written to the AWS.json options file. It still shows up in the user-data. Manual fix is manually copying the key from the user data and inserting into the options file.

**Comment by cat-box** [comment]
I've cherry-picked it into master since develop is undergoing re-factorization for a number of items and is not currently ready for deployment. Cheers!
