### ISSUE TITLE
If I already own a domain, does it work?

### ISSUE THREAD

**Issue by sutee9** [cat-box/aws-foundry-ssl#9]
I read your wiki, and didn't really understand if the approach would work if I already owned a domain (from a registrar not listed here). Could you maybe say how that works or specifically say it doesn't?

Just looking for clarity.

**Comment by cat-box** [comment]
No, it will not work. We use APIs to configure compatibility with domain registrars. It was unrealistic for us to script a method for all domain registrars out there so we chose four which we believed to be the most popular. You are free to either switch the nameservers to route53, or transfer your domain with a small fee.
